- alias: Notify me when a 3d print finishes
  id: 282d7e1b370b46bfa5aa73521d93d8d2
  trigger:
    platform: state
    entity_id: binary_sensor.octoprint_printing
    from: 'on'
    to: 'off'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.octoprint_camera
      filename: /config/www/camera/3d-print.jpg
  - service: notify.mobile_app_john_boiless_iphone_x
    data_template:
      message: 3D print has finished
      data:
        attachment:
          url: !secret 3d_print_snapshot_url
          image: !secret 3d_print_snapshot_url
          content-type: jpeg
          hide-thumbnail: false
- alias: Play Roll Over Easy on Thursday at 7:30a
  id: d585d760542f4186a44679bece1487d3
  trigger:
    platform: time
    at: 07:31:00
  condition:
  - condition: time
    weekday:
    - thu
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom
      volume_level: 0.3
  - service: media_player.play_media
    data:
      entity_id: media_player.bedroom
      media_content_id: BFF.fm
      media_content_type: TUNEIN
- alias: Turn off all lights in the house with a triple tap down in the dining room
  id: 1342127157ed4f988e2dfc5de60cfc69
  trigger:
    event_data:
      entity_id: zwave.dining_room_light
      scene_data: 4
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event
  action:
  - service: light.turn_off
    data:
      entity_id: group.all_lights
  - service: switch.turn_off
    data:
      entity_id: switch.bedroom_lamp_switch
  - service: switch.turn_off
    data:
      entity_id: switch.master_bathroom_fan_switch
- alias: Turn off common space lights with a triple tap down in the kitchen or bedroom
  id: 7f5929753d294d9596efe2446d9abf02
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_light
      scene_data: 4
      scene_id: 2
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_light
      scene_data: 4
      scene_id: 2
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_light_level
  - service: light.turn_off
    data:
      entity_id: light.kitchen_island_light_level
  - service: light.turn_off
    data:
      entity_id: light.dining_room_light_level
  - service: light.turn_off
    data:
      entity_id: light.dining_room_chandelier_level
  - service: light.turn_off
    data:
      entity_id: light.living_room_light_level
  - service: light.turn_off
    data:
      entity_id: light.kitchen_hallway_light_level
- alias: Turn on bedroom lamp with double tap up
  id: 08182ba3f3554d85a534a5b658d40104
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_light
      scene_id: 1
      scene_data: 3
  action:
    service: switch.turn_on
    data:
      entity_id: switch.bedroom_lamp_switch
- alias: Turn off bedroom lamp with double tap down
  id: 2c181ae14b514e0d9a520d8ab7fea07d
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_light
      scene_id: 2
      scene_data: 3
  action:
    service: switch.turn_off
    data:
      entity_id: switch.bedroom_lamp_switch
- alias: Garage Door Open Notification
  id: 33e78170ee6f40cbb028622f9a501a66
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
    for:
      minutes: 30
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.garage_door
  condition:
    condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data:
      message: Garage Door is Open
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: timer.start
    entity_id: timer.garage_door
- alias: Notify if sprinklers left on for 30 minutes
  id: c72b1caa51424d049a2f144c1160d7c7
  trigger:
  - platform: state
    entity_id:
    - switch.maple_sprinkler
    - switch.apple_and_lemon_sprinkler
    - switch.vegetable_box_sprinkler
    to: 'on'
    for:
      minutes: 30
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data:
      message: Sprinkler has been running for > 30 min
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
- alias: WD200 Status LED for Garage Door
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
  - platform: state
    entity_id: cover.garage_door
    to: closed
  action:
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 13 # Dimmer LED mode
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Status mode
        {%- else -%}
          Normal mode
        {%- endif -%}
  - service: zwave.set_config_parameter
    data_template:
      node_id: 21
      parameter: 21 # Status mode LED 1 (bottom) color
      value: >-
        {%- if trigger.to_state.state == 'open' -%}
          Red
        {%- else -%}
          White
        {%- endif -%}
- alias: Adjust dim level for WD100 lights when they are turned off afterhours
  id: 02ac6c6160e74ce2b91d7cd142cd4eda
  trigger:
  - platform: state
    entity_id:
    - light.living_room_light_level
    - light.dining_room_light_level
    - light.kitchen_island_light_level
    - light.kitchen_light_level
    - light.kitchen_hallway_light_level
    - light.bedroom_light_level
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: time
    after: '21:00:00'
    before: 06:00:00
  action:
    service: script.set_homeseer_dim_level
    data_template:
      entity_id: "{{ trigger.entity_id }}"
      brightness: >-
        {%- if trigger.entity_id == "light.kitchen_island_light_level" -%}
          50
        {%- else -%}
          3
        {%- endif -%}
- alias: Set dim level for lights at night
  id: fbd91d4f47f44fc4964c7b38d3a0b9a2
  trigger:
    platform: time
    at: '21:00:00'
  action:
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.living_room_light_level
      brightness: 3
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.dining_room_light_level
      brightness: 3
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_island_light_level
      brightness: 50
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_light_level
      brightness: 3
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_hallway_light_level
      brightness: 3
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.bedroom_light_level
      brightness: 3
  - service: zwave.set_config_parameter
    data_template:
      node_id: 24
      parameter: 17
      value: 15
- alias: Set bright level for lights in the morning
  id: 5414ebf2b25c4a0a88bb4115c6a2758d
  trigger:
    platform: time
    at: '7:00:00'
  action:
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.living_room_light_level
      brightness: 255
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.dining_room_light_level
      brightness: 255
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.dining_room_chandelier_level
      brightness: 255
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_island_light_level
      brightness: 255
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_light_level
      brightness: 255
  - service: script.set_homeseer_dim_level
    data:
      entity_id: light.kitchen_hallway_light_level
      brightness: 255
  - service: zwave.set_config_parameter
    data_template:
      node_id: 24
      parameter: 17
      value: 99
- alias: Push notify when power goes out
  id: d986a9e1de204037a6ea78c183f07fde
  trigger:
    platform: numeric_state
    entity_id: sensor.nut_ups_input_voltage
    below: 60
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data:
      message: Power is out
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: persistent_notification.create
    data:
      message: Power went out
      title: Power outage
- alias: Push notify when smoke alarm is triggered
  id: 906bd5f51b04474d85bfe5404251d03f
  trigger:
  - platform: state
    entity_id: sensor.basement_smoke_alarm_state
    from: Unknown
  - platform: state
    entity_id: sensor.basement_smoke_alarm_state
    from: Idle
  condition:
  - condition: template
    value_template: '{{ not is_state("sensor.basement_smoke_alarm_state", "Idle") }}'
  - condition: template
    value_template: '{{ not is_state("sensor.basement_smoke_alarm_state", "Unknown") }}'
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data:
      title: Smoke alarm
      message: Smoke alarm is triggered!
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: persistent_notification.create
    data:
      message: Smoke alarm is triggered!
      title: Smoke alarm
- alias: Update Available Notification
  id: 1002777a3e4d481caf6488391db7b01f
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data_template:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.
  - service: persistent_notification.create
    data_template:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.
      title: Update available
- alias: HACS Update Available Notification
  id: 76614c0d64b14e15b3c436d07d17b432
  trigger:
    platform: state
    entity_id: sensor.hacs
    from: '0'
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data_template:
      message: HACS has {{ trigger.to_state.state }} available update.
  - service: persistent_notification.create
    data_template:
      message: HACS has {{ trigger.to_state.state }} available update.
      title: HACS Update available
- alias: Unifi Firmware Available Notification
  id: 4b1f0b626a9049ab892a56f512106af7
  trigger:
    platform: state
    entity_id: sensor.unifi_gateway_firmware_upgradable
    from: '0'
  action:
  - service: notify.mobile_app_john_boiless_iphone_x
    data_template:
      message: New Unifi firmware is available.
  - service: persistent_notification.create
    data:
      message: New Unifi firmware is available.
      title: Update available
- alias: Unifi Gateway New Alerts Notification
  id: 8fae181b865a49a6bf04128f2e2e9c84
  trigger:
    platform: state
    entity_id: sensor.unifi_gateway_alerts
    from: '0'
  action:
    service: notify.mobile_app_john_boiless_iphone_x
    data_template:
      message: Unifi controller has new alerts.
- alias: Recalibrate CO2 when nobody is home
  id: a26603390cea4af5aadcdc483dc77d2b
  trigger:
  - platform: state
    entity_id: group.all_people
    to: not_home
    for:
      hours: 4
  - platform: state
    entity_id: group.all_occupancy
    to: 'off'
    for:
      hours: 4
  condition:
  - condition: state
    entity_id: group.all_people
    state: not_home
    for:
      hours: 4
  - condition: state
    entity_id: group.all_occupancy
    state: 'off'
    for:
      hours: 4
  action:
  - service: esphome.airsensor_mhz19_calibrate_zero
  - service: notify.mobile_app_john_boiless_iphone_x
    data:
      message: Calibrating CO2 sensor.
- alias: Water Backyard
  id: d3b9ce0c8a7f4527b200174e076f9213
  trigger:
  - platform: time
    at: 03:30:00
  action:
  - service: script.sprinkler_water_backyard
- alias: Soundbar to Aux when the Everywhere group is playing
  id: 230724d25e4c428d9370c15e120ebbf9
  trigger:
  - platform: state
    entity_id: media_player.everywhere
    to: playing
  - platform: state
    entity_id: media_player.everywhere
    from: playing
  - platform: state
    entity_id: media_player.living_room
    to: playing
  - platform: state
    entity_id: media_player.living_room
    from: playing
  action:
    service: esphome.ir_blaster_transmit_nec_string
    data_template:
      address: 0xFF
      command: >-
        {%- if trigger.to_state.state == 'playing' -%}
          0x8D72
        {%- else -%}
          0x13EC
        {%- endif -%}
- alias: Turn on Step lights With Bistro Lights
  id: '1591884118185'
  description: ''
  trigger:
  - device_id: a9fb08898aae4a7a81c1a9e68ea3cde6
    domain: light
    entity_id: light.backyard_bistro_lights_level
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      brightness: 70
      effect: Fake Surround Louvres
      rgb_color:
      - 255
      - 162
      - 71
      white_value: 36
    entity_id: light.backyard_step_lights
    service: light.turn_on
- alias: Turn off step lights with bistro lights
  id: '1591884206093'
  description: Turn off step lights with bistro lights
  trigger:
  - device_id: a9fb08898aae4a7a81c1a9e68ea3cde6
    domain: light
    entity_id: light.backyard_bistro_lights_level
    platform: device
    type: turned_off
  condition: []
  action:
  - data: {}
    entity_id: light.backyard_step_lights
    service: light.turn_off
