esphome:
  name: elijah_desk_lights
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Elijah Desk Lights"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

ota:

# Enable Home Assistant API
api:

light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO3
    num_leds: 83
    name: "Elijah Desk Lights"
    effects:
      - addressable_fireworks:
      - addressable_flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_random_twinkle:
      - addressable_twinkle:
      - addressable_twinkle:
          name: Custom Twinkle Effect
          twinkle_probability: 30%
          progress_interval: 4ms
